import { expect, test } from "@playwright/test";

test("core opportunity workflow", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "Opportunities" })).toBeVisible();
  const opportunityResponse = await page.request.get("/api/opportunities");
  expect(opportunityResponse.ok()).toBe(true);
  const opportunityBody = await opportunityResponse.json();
  expect(opportunityBody.provenance).toBe("recorded_live");
  expect(opportunityBody.data.length).toBeGreaterThan(5000);
  await expect(page.getByLabel("Status filter")).toHaveValue("open");
  await expect(page.getByRole("complementary")).toHaveCount(0);
  await page.getByLabel("Status filter").selectOption("all");
  await expect(page.getByText("NSW Roadmap - Tender Round 9").first()).toBeVisible();
  await page.getByText("NSW Roadmap - Tender Round 9").first().click();
  await page.getByRole("button", { name: "Raw" }).click();
  await expect(page.getByText("Immutable source row")).toBeVisible();
  await expect(page.getByText("Completed Bright Data custom collector dataset run")).toBeVisible();
  await page.getByRole("button", { name: /Changes/ }).click();
  await expect(page.getByRole("heading", { name: "No material changes observed" })).toBeVisible();
  const detail = page.getByRole("complementary");
  await expect(detail.getByRole("button", { name: "Workspace" })).toHaveCount(0);
  await detail.getByRole("button", { name: "Copilot", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Reason over this opportunity—not the open web." })).toBeVisible();
  await expect(page.getByText("Evidence in scope")).toBeVisible();
});

test("filters and one-click live operations", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "Opportunities" })).toBeVisible({ timeout: 30_000 });
  await expect(page.getByLabel("Status filter")).toHaveValue("open");
  const response = await page.request.get("/api/opportunities");
  const opportunities = (await response.json()) as { data: Array<{ status: string }> };
  const openCount = opportunities.data.filter((item) => item.status === "open").length;
  await expect(page.getByText(`${openCount} opportunities`)).toBeVisible();
  await expect(page.getByRole("button", { name: "Find more opportunities" })).toBeEnabled();
  await page.locator(".advanced-filters summary").click();
  await page.getByLabel("Buyer or agency").fill("Transportation");
  await expect(page.locator(".result-count strong")).not.toHaveText(String(openCount));
  await page.getByRole("button", { name: "Clear advanced filters" }).click();
  await page.getByLabel("Status filter").selectOption("all");
  await page.getByLabel("Country filter").selectOption("AU");
  await expect(page.getByText("Capacity Investment Scheme NEM Dispatchable").first()).toBeVisible();
  await page.getByRole("button", { name: "Operations" }).click();
  await expect(page.getByRole("heading", { name: "Sources", exact: true })).toBeVisible();
  const sourceResponse = await page.request.get("/api/sources");
  expect(sourceResponse.ok()).toBe(true);
  const body = (await sourceResponse.json()) as {
    data: Array<{ slug: string; latestRun: { validRowCount: number; metrics: { dateParseRate: number } } | null }>;
  };
  const asl = body.data.find((source) => source.slug === "australia-asl-tenders");
  expect(asl?.latestRun?.validRowCount).toBe(4);
  expect(asl?.latestRun?.metrics.dateParseRate).toBe(1);
  await expect(page.getByRole("button", { name: "Run all live sources" })).toBeEnabled();
  await expect(page.getByText("CanadaBuys tender opportunities")).toBeVisible();
  await expect(page.getByText("VendorPanel Australian public tenders")).toBeVisible();
  await expect(page.getByText("Québec SEAO open calls for tenders")).toBeVisible();
  await expect(page.getByText("Texas DOT official bid projects")).toBeVisible();
  await expect(page.getByText("Los Angeles RAMP open bid opportunities")).toBeVisible();
  await expect(page.getByText("EU TED open procurement notices")).toBeVisible();
  await expect(page.getByText("City of Chicago active solicitations")).toBeVisible();
  await expect(page.getByText("New York City current bids")).toBeVisible();
  await expect(page.getByText("Montgomery County active solicitations")).toBeVisible();
  await expect(page.getByText("San Francisco open bid opportunities")).toBeVisible();
  await expect(page.getByRole("button", { name: "Source unavailable" })).toBeDisabled();
  await expect(page.getByText("882 rows · 882 valid")).toBeVisible();
  await expect(page.getByText("700 rows · 700 valid")).toBeVisible();
  await expect(page.getByText("342 rows · 342 valid")).toBeVisible();
  await expect(page.getByText("391 rows · 391 valid")).toBeVisible();
  await expect(page.getByText("89 rows · 89 valid")).toBeVisible();
  await expect(page.getByText("39593 rows · 39593 valid")).toBeVisible();
  await expect(page.getByText("50 rows · 50 valid")).toBeVisible();
  await expect(page.getByText("2 verified scraper repairs")).toBeVisible();
  await expect(page.getByLabel("Operator secret")).toHaveCount(0);
});
