import { z } from 'zod';
import { buildCopilotContext, type ApplicationContext, type VendorProfile } from '../context.js';
import { secureContractSystemPrompt } from '../system-prompt.js';
import type { Opportunity } from '../../../types.js';
export interface SecureContractCopilotResponse { answer:string; evidenceFields:string[]; opportunityIds:string[]; draft:boolean; }
export type CopilotHistoryTurn = { role:'user'|'assistant'; content:string; };
export interface CopilotProvider { chat(request:{question:string;history?:CopilotHistoryTurn[];opportunity:Opportunity;relatedOpportunities?:Opportunity[];vendor?:VendorProfile;workspace?:ApplicationContext;mode?:'search'|'record'}):Promise<SecureContractCopilotResponse>; }
const responseSchema=z.object({answer:z.string().min(1),evidenceFields:z.array(z.string()),opportunityIds:z.array(z.string()).default([]),draft:z.boolean()});
const historySchema=z.array(z.object({role:z.enum(['user','assistant']),content:z.string().min(1)})).max(12);
const compact=(value:unknown):unknown=>{if(Array.isArray(value))return value.map((item)=>compact(item)).filter((item)=>{if(item===null||item===undefined||item==='')return false;if(Array.isArray(item)&&item.length===0)return false;if(typeof item==='object'&&item!==null&&!Array.isArray(item)&&Object.keys(item).length===0)return false;return true});if(value&&typeof value==='object'){const out:Record<string,unknown>={};for(const[key,item]of Object.entries(value as Record<string,unknown>)){const cleaned=compact(item);if(cleaned===null||cleaned===undefined||cleaned===''||(Array.isArray(cleaned)&&cleaned.length===0)||(typeof cleaned==='object'&&cleaned!==null&&!Array.isArray(cleaned)&&Object.keys(cleaned).length===0))continue;out[key]=cleaned;}return out;}return value;};
export class NvidiaNimProvider implements CopilotProvider {
  constructor(private config:{apiKey:string;baseUrl:string;model:string}, private fetcher:typeof fetch=fetch) {}
  async chat(request:{question:string;history?:CopilotHistoryTurn[];opportunity:Opportunity;relatedOpportunities?:Opportunity[];vendor?:VendorProfile;workspace?:ApplicationContext;mode?:'search'|'record'}) {
    const fullContext=buildCopilotContext(request.opportunity,request.vendor,request.workspace);
    const context=request.relatedOpportunities?{...fullContext,opportunity:{...fullContext.opportunity,description:fullContext.opportunity.description?.slice(0,1200)},evidence:fullContext.evidence.slice(0,8).map(({fieldName,normalizedValue,sourceUrl})=>({fieldName,normalizedValue,sourceUrl})),changes:[],application:null,vendor:null}:fullContext;
    const related=(request.relatedOpportunities??[]).slice(0,10).map((item)=>({id:item.id,title:item.titleOriginal,buyer:item.buyerOriginal,status:item.status,country:item.countryName,jurisdiction:item.jurisdiction,countryCode:item.countryCode,sourceId:item.sourceId,deadline:item.submissionDueAt,timezone:item.localTimezone,publishedAt:item.publishedAt,estimatedValue:item.estimatedValueMinor&&item.currency?`${item.currency} ${(Number(item.estimatedValueMinor)/100).toLocaleString('en-US')}`:null,procedureType:item.procedureTypeOriginal??item.procedureType,registrationRequired:item.registrationRequired,eligibilitySummary:item.eligibilitySummary?.slice(0,300)??null,sourceUrl:item.sourceUrl,detailUrl:item.detailUrl,description:(item.descriptionEnglish??item.descriptionOriginal??'').slice(0,1200),industryCodes:item.industryCodes.map(({system,code,label})=>({system,code,label})),evidence:item.evidence.slice(0,4).map(({fieldName,normalizedValue,sourceUrl})=>({fieldName,normalizedValue,sourceUrl}))}));
    const history=historySchema.parse(request.history??[]).slice(-8);
    const searchMode=request.mode==='search'||(!request.mode&&Boolean(request.relatedOpportunities?.length));
    const modeInstructions=searchMode
      ?'Mode: search. There is no user-selected contract; the selectedContract field is just the top-ranked record. Base recommendations on searchCandidates, never call anything "the selected contract", and speak about the record set as a whole. When the question is about what a type of work involves or how to apply, compare the candidate records and describe the common scope, deliverables, and application routes they share.'
      :      'Mode: record. The user has one specific contract open; use its selectedContract JSON and evidence first, and treat searchCandidates as comparable solicitations that show what similar buyers ask for. When useful, add two short analytical passages grounded in the supplied fields, each hedged with "likely" where you infer beyond the data: first, what delivering this work would probably involve (work streams, logistics, compliance angles from industryCodes, description, buyer type, jurisdiction); second, realistic ways to apply (registration steps from registrationRequired and sourceUrl, documents to prepare, questions deadline, prebid meetings, evidence typically expected for this procedureType). Never present inferred requirements as confirmed. Summarize the record naturally — never recite field-by-field data, urls, or ids in prose.';
    const response=await this.fetcher(`${this.config.baseUrl}/chat/completions`,{method:'POST',headers:{Authorization:`Bearer ${this.config.apiKey}`,'Content-Type':'application/json'},signal:AbortSignal.timeout(45_000),body:JSON.stringify({model:this.config.model,temperature:0.1,max_tokens:1400,response_format:{type:'json_object'},messages:[{role:'system',content:secureContractSystemPrompt},...history.map(({role,content})=>({role,content})),{role:'user',content:JSON.stringify({mode:request.mode??(searchMode?'search':'record'),question:request.question,selectedContract:compact(context),searchCandidates:related.map((item)=>compact(item)),instructions:`${modeInstructions} Resolve follow-up questions using the earlier turns of this conversation. Write as a senior procurement advisor sharing what genuinely matters: surface key facts from the supplied JSON such as deadlines, buyers, estimated values, eligibility notes, and scope, and briefly explain what they mean for a potential bidder. Plain conversational text only: the interface renders raw strings, so never use markdown syntax, asterisks, hashes, or code fences; use short paragraphs, and reserve dash lists for enumerating records. Keep prose natural: never enumerate evidence field names, never paste raw ids or urls in sentences; when mentioning comparable records use their buyer and title (ids belong only in opportunityIds). Always name records by buyer and title, and list the exact id of every recommended record in opportunityIds (include several when several qualify). End with one concrete next step. Return answer, evidenceFields, opportunityIds, and draft as JSON without a reasoning trace.`})}]})});
    if(!response.ok) throw new Error(`NVIDIA NIM request failed (${response.status})`);
    const body=await response.json() as {choices?:Array<{message?:{content?:string}}>}; const content=body.choices?.[0]?.message?.content;
    if(!content) throw new Error('NVIDIA NIM returned no content');
    const parsed=responseSchema.parse(JSON.parse(content.replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'')));
    const evidenceFields=new Map(context.evidence.map((item)=>[item.fieldName.toLowerCase(),item.fieldName]));
    const groundedFields=[...new Set(parsed.evidenceFields.map((field)=>evidenceFields.get(field.trim().toLowerCase())).filter((field):field is string=>Boolean(field)))];
    const allowedIds=new Set([request.opportunity.id,...(request.relatedOpportunities??[]).map((item)=>item.id)]);
    return {...parsed,evidenceFields:groundedFields,opportunityIds:[...new Set(parsed.opportunityIds.filter((id)=>allowedIds.has(id)))]};
  }
}
