import { integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

export const sourceStatus = pgEnum('source_status',['draft','active','warning','degraded','disabled']);
export const runStatus = pgEnum('run_status',['pending','healthy','warning','degraded','failed']);
export const appStatus = pgEnum('application_status',['not_started','reviewing','preparing','ready_for_review','submitted_manually','archived']);
export const taskStatus = pgEnum('task_status',['todo','done','blocked']);

export const sources = pgTable('sources',{ id:uuid('id').defaultRandom().primaryKey(), slug:text('slug').notNull().unique(), name:text('name').notNull(), countryCode:text('country_code').notNull(), countryName:text('country_name').notNull(), jurisdictionType:text('jurisdiction_type').notNull(), jurisdictionName:text('jurisdiction_name'), locale:text('locale').notNull(), timezone:text('timezone').notNull(), currency:text('currency'), sourceLanguage:text('source_language').notNull(), sourceUrl:text('source_url').notNull(), inputUrl:text('input_url').notNull(), collectorId:text('collector_id'), adapterKey:text('adapter_key').notNull(), status:sourceStatus('status').default('draft').notNull(), requiredFields:jsonb('required_fields').$type<string[]>().default([]).notNull(), publicAccessVerifiedAt:timestamp('public_access_verified_at',{withTimezone:true}), prebuiltLibraryCheckedAt:timestamp('prebuilt_library_checked_at',{withTimezone:true}), createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull() });
export const sourceRuns = pgTable('source_runs',{ id:uuid('id').defaultRandom().primaryKey(), sourceId:uuid('source_id').references(()=>sources.id).notNull(), collectionId:text('collection_id'), status:runStatus('status').default('pending').notNull(), rowCount:integer('row_count'), validRowCount:integer('valid_row_count'), metrics:jsonb('metrics'), problems:jsonb('problems').$type<string[]>().default([]).notNull(), startedAt:timestamp('started_at',{withTimezone:true}).defaultNow().notNull(), finishedAt:timestamp('finished_at',{withTimezone:true}) });
export const rawRecords = pgTable('raw_records',{ id:uuid('id').defaultRandom().primaryKey(), sourceRunId:uuid('source_run_id').references(()=>sourceRuns.id).notNull(), sourceId:uuid('source_id').references(()=>sources.id).notNull(), recordIndex:integer('record_index').notNull(), raw:jsonb('raw').notNull(), rawHash:text('raw_hash').notNull(), observedAt:timestamp('observed_at',{withTimezone:true}).defaultNow().notNull() }, table=>[uniqueIndex('raw_record_run_index').on(table.sourceRunId,table.recordIndex)]);
export const opportunities = pgTable('opportunities',{ id:text('id').primaryKey(), sourceId:uuid('source_id').references(()=>sources.id).notNull(), externalId:text('external_id'), canonical:jsonb('canonical').notNull(), contentHash:text('content_hash').notNull(), currentVersionId:uuid('current_version_id'), firstSeenAt:timestamp('first_seen_at',{withTimezone:true}).defaultNow().notNull(), lastSeenAt:timestamp('last_seen_at',{withTimezone:true}).defaultNow().notNull() });
export const opportunityVersions = pgTable('opportunity_versions',{ id:uuid('id').defaultRandom().primaryKey(), opportunityId:text('opportunity_id').references(()=>opportunities.id).notNull(), sourceRunId:uuid('source_run_id').references(()=>sourceRuns.id).notNull(), canonical:jsonb('canonical').notNull(), contentHash:text('content_hash').notNull(), observedAt:timestamp('observed_at',{withTimezone:true}).defaultNow().notNull() });
export const opportunityChanges = pgTable('opportunity_changes',{ id:uuid('id').defaultRandom().primaryKey(), opportunityId:text('opportunity_id').references(()=>opportunities.id).notNull(), versionId:uuid('version_id').references(()=>opportunityVersions.id).notNull(), fieldName:text('field_name').notNull(), oldValue:jsonb('old_value'), newValue:jsonb('new_value'), severity:text('severity').notNull(), observedAt:timestamp('observed_at',{withTimezone:true}).defaultNow().notNull() });
export const fieldEvidence = pgTable('field_evidence',{ id:uuid('id').defaultRandom().primaryKey(), opportunityId:text('opportunity_id').references(()=>opportunities.id).notNull(), versionId:uuid('version_id').references(()=>opportunityVersions.id).notNull(), fieldName:text('field_name').notNull(), normalizedValue:jsonb('normalized_value'), rawLabel:text('raw_label'), rawValue:text('raw_value'), sourceUrl:text('source_url').notNull(), observedAt:timestamp('observed_at',{withTimezone:true}).notNull(), confidence:text('confidence').notNull() });
export const documents = pgTable('documents',{ id:uuid('id').defaultRandom().primaryKey(), opportunityId:text('opportunity_id').references(()=>opportunities.id).notNull(), name:text('name').notNull(), url:text('url').notNull(), metadata:jsonb('metadata') });
export const amendments = pgTable('amendments',{ id:uuid('id').defaultRandom().primaryKey(), opportunityId:text('opportunity_id').references(()=>opportunities.id).notNull(), label:text('label').notNull(), url:text('url'), observedAt:timestamp('observed_at',{withTimezone:true}).notNull() });
export const vendorProfiles = pgTable('vendor_profiles',{ id:uuid('id').defaultRandom().primaryKey(), companyName:text('company_name').notNull(), profile:jsonb('profile').notNull(), updatedAt:timestamp('updated_at',{withTimezone:true}).defaultNow().notNull() });
export const applicationWorkspaces = pgTable('application_workspaces',{ id:uuid('id').defaultRandom().primaryKey(), opportunityId:text('opportunity_id').references(()=>opportunities.id).notNull().unique(), status:appStatus('status').default('not_started').notNull(), notes:text('notes'), createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull(), updatedAt:timestamp('updated_at',{withTimezone:true}).defaultNow().notNull() });
export const applicationTasks = pgTable('application_tasks',{ id:uuid('id').defaultRandom().primaryKey(), workspaceId:uuid('workspace_id').references(()=>applicationWorkspaces.id).notNull(), label:text('label').notNull(), status:taskStatus('status').default('todo').notNull(), evidenceId:uuid('evidence_id').references(()=>fieldEvidence.id), createdBy:text('created_by').notNull(), createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull() });
export const copilotThreads = pgTable('copilot_threads',{ id:uuid('id').defaultRandom().primaryKey(), workspaceId:uuid('workspace_id').references(()=>applicationWorkspaces.id).notNull(), createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull() });
export const copilotMessages = pgTable('copilot_messages',{ id:uuid('id').defaultRandom().primaryKey(), threadId:uuid('thread_id').references(()=>copilotThreads.id).notNull(), role:text('role').notNull(), content:text('content').notNull(), evidenceIds:jsonb('evidence_ids').$type<string[]>().default([]).notNull(), createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull() });
